# Generated by Django 2.0.4 on 2018-04-16 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_books_book_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AddField(
            model_name='books',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
