# Generated by Django 2.0.4 on 2018-04-22 14:43

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180417_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=webapp.models.upload_location),
        ),
    ]
