# Generated by Django 2.0.4 on 2018-04-27 18:34

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20180422_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='epub',
            field=models.FileField(blank=True, null=True, upload_to=webapp.models.upload_location),
        ),
    ]
