# Generated by Django 2.0.4 on 2018-04-29 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_books_epub'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='epub',
            field=models.FileField(blank=True, null=True, upload_to='epub/'),
        ),
    ]
