# Generated by Django 2.0.4 on 2018-04-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20180430_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='epub',
        ),
        migrations.AddField(
            model_name='books',
            name='epub_cyrillic',
            field=models.FileField(blank=True, null=True, upload_to='epub_cyrillic/'),
        ),
        migrations.AddField(
            model_name='books',
            name='epub_latin',
            field=models.FileField(blank=True, null=True, upload_to='epub_latin/'),
        ),
    ]
