# Generated by Django 2.0.4 on 2018-05-01 14:10

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20180501_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, null=True, upload_to=webapp.models.upload_location)),
                ('epub_cyrillic', models.FileField(blank=True, null=True, upload_to='epub_cyrillic/')),
                ('epub_latin', models.FileField(blank=True, null=True, upload_to='epub_latin/')),
                ('description', models.TextField()),
                ('section_id', models.IntegerField(default=0)),
                ('section_name', models.CharField(default='null', max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
